### ISSUE TITLE
Unexpected identifier error

### ISSUE THREAD

**Issue by markronquillo** [ElementsProject/lightning-charge#15]
Good day,

Sorry if this is a noob question.

I've already setup `bitcoind` and `lightningd` in my machine.

The problem is whenever I run `charged` or `charged --api-token mytokenhere` it shows this error.

```
exports.down = async db => {
                     ^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:136:25
    at arrayFilter (/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/lodash/_arrayFilter.js:18:9)
    at filter (/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/lodash/filter.js:45:10)
    at /home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:135:112
    at tryCatcher (/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:569:18)
/home/bitcoin/.npm-global/lib/node_modules/lightning-charge/migrations/20180120115425_completed-fields.js:8

```

Thanks

**Comment by mautematico** [comment]
Hola Joseph.

Which node version are you using?

**Comment by markronquillo** [comment]
Hi mautematico

I am using Node v6.12.3

Thanks

**Comment by mautematico** [comment]
Please try with node v7+. AFAIK, async was introduced there.

**Comment by markronquillo** [comment]
Got it thanks for the help!

**Comment by shesek** [comment]
Added the nodejs 8 requirement to the README.

Lightning Charge could be made to work on older nodejs versions quite easily, by changing [babel's transpilation target](https://babeljs.io/docs/plugins/preset-env/#targets). If anyone stumbles upon this issue and wants this, let me know and I'll look into that.
