### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by otaviobps** [ElementsProject/lightning-charge#16]
Running charged gives me this error:

```
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/usr/local/lib/node_modules/lightning-charge/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/usr/local/lib/node_modules/lightning-charge/node_modules/knex/lib/client.js:249:26)
    at Client_SQLite3.Client (/usr/local/lib/node_modules/lightning-charge/node_modules/knex/lib/client.js:126:10)
    at new Client_SQLite3 (/usr/local/lib/node_modules/lightning-charge/node_modules/knex/lib/dialects/sqlite3/index.js:62:20)
```
I tried to find the node-v57-linux-x64 folder, but I could only find the node-v48-linux-x64 folder instead.

**Comment by shesek** [comment]
Is it possible that you changed node versions between installing lightning-charge and running it?

Can you try deleting and re-installing the package, making sure you're running it with the same node version that installed it?

**Comment by otaviobps** [comment]
Yes, actually I did it. I had node version 6.x and then installed version 8.x

I uninstalled lightning-charge by `npm uninstall -g lightning-charge` and then reinstalled it. Lightning-charge is installing this node module under `/home/node/.npm-global/lib/node_modules/lightning-charge/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node` but when I run `charged` it searches under `/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node`

**Comment by shesek** [comment]
It looks like you also have lightning-charge installed as a system-wide package.

Can you try running uninstall with sudo (`sudo uninstall -g lightning-charge`) and see if that makes a difference?

**Comment by otaviobps** [comment]
Running `sudo npm uninstall -g lightning-charge` gives me this error:

```
sudo npm uninstall -g lightning-charge
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/shesek/lightning-client-js.git /home/node/.npm/_cacache/tmp/git-clone-784d46e1
npm ERR! /home/node/.npm/_cacache/tmp/git-clone-784d46e1/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-01-24T13_25_34_349Z-debug.log
```

**Comment by shesek** [comment]
What does ```ls -l `which charged` ``` return?

**Comment by shesek** [comment]
Hmm, actually, just `which charged`.

**Comment by otaviobps** [comment]
```
ls -l which charged
ls: cannot access 'which': No such file or directory
ls: cannot access 'charged': No such file or directory
```

**Comment by shesek** [comment]
It was supposed to be ```ls -l `which charged` ``` (including the ``` ` ```), but I actually just need `which charged`.

**Comment by otaviobps** [comment]
```
ls -l 'which charged'
ls: cannot access 'which charged': No such file or directory

```

**Comment by otaviobps** [comment]
Sorry, actually gives me this:

```
node@node-MacBook:~$ ls -l `which charged`
lrwxrwxrwx 1 root root 48 jan 24 10:01 /usr/local/bin/charged -> ../lib/node_modules/lightning-charge/bin/charged

```

**Comment by shesek** [comment]
It's ``` ` ``` (a backtick), not `'` (a single quote), but just `which charged` alone is enough -- no need for the `ls`.

**Comment by otaviobps** [comment]
Yes, corrected it

```
node@node-MacBook:~$ ls -l `which charged`
lrwxrwxrwx 1 root root 48 jan 24 10:01 /usr/local/bin/charged -> ../lib/node_modules/lightning-charge/bin/charged
```

**Comment by shesek** [comment]
Okay, great! Try removing the system-wide installation with this:

```bash
$ rm /usr/local/bin/charged
$ rm -rf /usr/local/lib/node_modules/lightning-charge
```

Then try running `charged` again.

**Comment by otaviobps** [comment]
I had to reinstall `charged` again, but when I run `npm install -g lightning-charge` it gives me permission errors:

```
~$ npm install -g lightning-charge
npm WARN checkPermissions Missing write access to /home/node/.npm-global/lib
npm ERR! path /home/node/.npm-global/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/node/.npm-global/lib'
npm ERR!  { Error: EACCES: permission denied, access '/home/node/.npm-global/lib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/node/.npm-global/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/node/.npm-global/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by shesek** [comment]
Are you running this as the user `node`?

Does `chown -R node:node /home/node/.npm-global` help?

**Comment by otaviobps** [comment]
Yes, user is `node`. I could install `charged` now, but when I run it, it doesn't find the directory:

```
~$ charged --api-token=xxx --NETWORK=bitcoin
bash: /usr/local/bin/charged: No such file or directory

```

**Comment by shesek** [comment]
Try re-opening your terminal, I believe this is just a cache that remembers `/usr/local/bin/charged` used to exists.

Note that lightning charge doesn't have a `network` option, it will be running on whatever network the `bitcoind`/`lightningd` instances are running on. (the `NETWORK` option you saw on the README was for Docker, which is used to configure `bitcoind` and `lightningd`, not charge itself)

**Comment by otaviobps** [comment]
Okay, thank you, removed the flag `network`. Closed the terminal and reopened it:

```
~$ charged --api-token xxx
No command 'charged' found, did you mean:
 Command 'charge' from package 'emboss' (universe)
charged: command not found
```

**Comment by shesek** [comment]
Do you have `~/.npm-global` in your `PATH`? Did you follow step 4 [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory)?

Try running `~/.npm-global/bin/charged --help`. If this works, then you should configure your `PATH` as explained in the link.

**Comment by otaviobps** [comment]
Hmm strange. I did have `~/.npm-global` in my `PATH`.

`~/.npm-global/bin/charged --help` did help, so I updated my system variables and it worked!

Thank you very much for your help. I'm closing this issue.

Thanks again

**Comment by shesek** [comment]
You're welcome!

**Comment by Muhammad-Yameen** [comment]
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (E:\Nodejs\yardstick\node_modules\knex\lib\dialects\sqlite3\index.js:79:12)
    at Client_SQLite3.initializeDriver (E:\Nodejs\yardstick\node_modules\knex\lib\client.js:240:26)
    at Client_SQLite3.Client (E:\Nodejs\yardstick\node_modules\knex\lib\client.js:115:10)
    at new Client_SQLite3 (E:\Nodejs\yardstick\node_modules\knex\lib\dialects\sqlite3\index.js:62:20)
    at Knex (E:\Nodejs\yardstick\node_modules\knex\lib\index.js:60:34)
    at new Database (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\src\Database\index.js:80:17)
    at DatabaseManager.connection (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\src\Database\Manager.js:81:35)
    at Object.get (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\lib\proxyGet.js:40:77)
    at Migration._makeMigrationsTable (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\src\Migration\index.js:46:36)
    at Migration.up (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\src\Migration\index.js:319:16)
    at MigrationRun.handle (E:\Nodejs\yardstick\node_modules\@adonisjs\lucid\commands\MigrationRun.js:63:66)
    at Promise (E:\Nodejs\yardstick\node_modules\@adonisjs\ace\src\Command\index.js:560:48)

**Comment by Muhammad-Yameen** [comment]
I have same issue please guide

**Comment by alexaumaitre** [comment]
I have the same problem. No way to make it works !

**Comment by shesek** [comment]
@alexaumaitre How are you installing charge? Have you tried following the instructions at https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory?
