### ISSUE TITLE
Correctly handle 0 value invoices

### ISSUE THREAD

**Issue by alecalve** [ElementsProject/lightning-charge#25]
These should be rejected I think.

```
LightningError: '0' is not a valid positive number  
    at createError (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/error/typed.js:31:22)                                                                                               
    at LightningClient.once.res (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:109:28)                                                                      
    at Object.onceWrapper (events.js:272:13)        
    at LightningClient.emit (events.js:180:13)      
    at Parser.LightningClient.parser.onValue (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:59:17)                                                          
    at Parser.proto.emit (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:337:8)                                                                                 
    at Parser.proto.pop (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:332:8)                                                                                  
    at Parser.proto.onToken (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:402:12)                                                                             
    at Parser.proto.write (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:135:34)                                                                               
    at Socket.LightningClient.client.on.data (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:54:53)                                                          
    at Socket.emit (events.js:180:13)               
    at addChunk (_stream_readable.js:269:12)        
    at readableAddChunk (_stream_readable.js:256:11)                                                     
    at Socket.Readable.push (_stream_readable.js:213:10)                                                 
    at Pipe.onread (net.js:581:20)
```

**Comment by alecalve** [comment]
See also https://github.com/ElementsProject/nanotip/issues/3 for incorrect handling of invoices with ridiculously high amounts.

**Comment by shesek** [comment]
They already are rejected by the underlying c-lightning. Or did you mean that Lightning Charge should reject them without passing them down to c-lightning?

I also just pushed a related update (https://github.com/ElementsProject/lightning-charge/commit/3bbc5a593df7ae53698e5d89de6fcc1563107803) which rounds msatoshi amounts up, so that tiny fiat amounts are rounded up to 1 msatoshi rather than to 0.

**Comment by alecalve** [comment]
They display as a stracktrace in the output of `charged` when the error should be sent to the user IMHO instead (for now you get an ugly "Internal Server Error").

**Comment by shesek** [comment]
You're indeed correct, these `LightningError`s should be sent to the user. Created #28 to keep track of that.

Assuming this is done, is there anything else that you think should be changed regarding the handling of 0 value amounts?

**Comment by alecalve** [comment]
I think sending an error message to the user is enough.

**Comment by shesek** [comment]
Alright, closing this then. Thanks for the feedback!
