### ISSUE TITLE
Unexpected identifier error being thrown when evaluating CLI params

### ISSUE THREAD

**Issue by martinbehrens** [ElementsProject/lightning-charge#46]
Running the following versions on a Centos 7.5.1804 box:

```
node v6.14.3
charged 0.4.0
```

Steps to reproduce:

Except for #45 trying to start charged with either:

```
charged --api-token NstxQtqsWHubkdbimZ --ln-path /home/username/.lightning --max-wait 90 --port 9112 --host xxx.xxx.xxx.xxx
charged --api-token NstxQtqsWHubkdbimZ --ln-path /home/username/.lightning --port 9112 --host xxx.xxx.xxx.xxx
charged --api-token NstxQtqsWHubkdbimZ --ln-path /home/username/.lightning/ --host xxx.xxx.xxx.xxx
charged --api-token NstxQtqsWHubkdbimZ --host xxx.xxx.xxx.xxx
charged --api-token NstxQtqsWHubkdbimZ --host 0.0.0.0
charged --api-token NstxQtqsWHubkdbimZ
charged --api-token NstxQtqsWHubk

charged -t NstxQtqsWHubkdbimZ -l /home/username/.lightning/ -d /home/username/.charged/sqlite.db -w 90 -p 9112 -i xxx.xxx.xxx.xxx
charged -t NstxQtqsWHubkdbimZ -l /home/username/.lightning/ -d ./.charged/sqlite.db -w 90 -p 9112 -i xxx.xxx.xxx.xxx
charged -t NstxQtqsWHubkdbimZ -l /home/username/.lightning -d ./.charged -w 90 -p 9112 -i xxx.xxx.xxx.xxx
charged -t NstxQtqsWHubkdbimZ -l /home/username/.lightning -w 90 -p 9112 -i xxx.xxx.xxx.xxx
charged -t NstxQtqsWHubkdbimZ -i xxx.xxx.xxx.xxx
charged -t NstxQtqsWHubkdbimZ
charged -t 1127589647 -l /home/username/.lightning -d /home/username/.charged/sqlite.db -w 90 -p 9112 -i xxx.xxx.xxx.xxx
charged -t 1127589647 -l /home/username/.lightning -d /home/username/.charged/sqlite.db -w 90 -p 9112 -i 0.0.0.0
charged -t 1127589647 -i 0.0.0.0
charged -t 1127589647 -l /home/username/.lightning -d /home/username/.charged/sqlite.db -w 90 -p 9112 -i 0.0.0.0
charged -t 1127589647 -l /home/username/.lightning --db-path ./charge.db -w 90 -p 9112 -i 0.0.0.0
```

... results in the following error being thrown:

```
/usr/lib/node_modules/lightning-charge/migrations/20180120115425_completed-fields.js:8
exports.down = async db => {
                     ^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:137:25
    at arrayFilter (/usr/lib/node_modules/lightning-charge/node_modules/knex/node_modules/lodash/_arrayFilter.js:18:9)
    at filter (/usr/lib/node_modules/lightning-charge/node_modules/knex/node_modules/lodash/filter.js:45:10)
    at /usr/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:136:112
    at tryCatcher (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:569:18)
/usr/lib/node_modules/lightning-charge/migrations/20180120115425_completed-fields.js:8
exports.down = async db => {
                     ^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:137:25
    at arrayFilter (/usr/lib/node_modules/lightning-charge/node_modules/knex/node_modules/lodash/_arrayFilter.js:18:9)
    at filter (/usr/lib/node_modules/lightning-charge/node_modules/knex/node_modules/lodash/filter.js:45:10)
    at /usr/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:136:112
    at tryCatcher (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by martinbehrens** [comment]
Argh, sorry. I assumed since all packages were up to date node was also the latest version. Anyway, the above was working fine but one has to remove the old version first with `sudo yum remove -y nodejs npm`.
